#!/usr/bin/env python3
"""Generate package metadata, service manifests, and Luau client types."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "thread.config.json"
LUAU_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
DOC_VERSION_PATTERN = re.compile(r'(<span class="version">)v[^<]+(</span>)')


def render_luau_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_metadata(config: dict) -> str:
    package = config["package"]
    authors = ", ".join(render_luau_string(author) for author in package["authors"])
    return f'''--!strict
-- Generated by scripts/generate.py. Do not edit directly.

return table.freeze({{
\tName = {render_luau_string(package["name"])},
\tVersion = {render_luau_string(package["version"])},
\tDescription = {render_luau_string(package["description"])},
\tLicense = {render_luau_string(package["license"])},
\tAuthors = table.freeze({{ {authors} }}),
}})
'''


def signal_arguments(details: list | dict) -> list[str]:
    return details.get("arguments", []) if isinstance(details, dict) else details


def render_client_types(config: dict) -> str:
    lines = [
        "--!strict",
        "-- Generated by scripts/generate.py. Do not edit directly.",
        "",
        "export type Signal<T... = ...any> = {",
        "\tFire: (self: Signal<T...>, T...) -> (),",
        "\tConnect: (self: Signal<T...>, (T...) -> ()) -> RBXScriptConnection,",
        "}",
        "export type Property<T> = {",
        "\tGet: (self: Property<T>) -> T,",
        "\tObserve: (self: Property<T>, (T) -> ()) -> { Disconnect: (self: any) -> () },",
        "}",
        "",
    ]
    service_names = []
    for service_name, service in sorted(config.get("services", {}).items()):
        service_names.append(service_name)
        lines.append(f"export type {service_name} = {{")
        for method_name, method in sorted(service.get("methods", {}).items()):
            args = ", ".join(method.get("arguments", []))
            returns = ", ".join(method.get("returns", []))
            lines.append(f"\t{method_name}: (self: {service_name}, {args}) -> ({returns})," if args else f"\t{method_name}: (self: {service_name}) -> ({returns}),")
        for signal_name, details in sorted(service.get("signals", {}).items()):
            arguments = signal_arguments(details)
            argument_types = ", ".join(arg.split(":", 1)[-1].strip() for arg in arguments) or "...any"
            lines.append(f"\t{signal_name}: Signal<{argument_types}>,")
        for property_name, property_type in sorted(service.get("properties", {}).items()):
            lines.append(f"\t{property_name}: Property<{property_type}>,")
        lines.extend(["}", ""])
    if service_names:
        lines.append("export type Services = {")
        for service_name in service_names:
            lines.append(f"\t{service_name}: {service_name},")
        lines.append("}")
    else:
        lines.append("export type Services = {}")
    lines.extend(["", "return table.freeze({})", ""])
    return "\n".join(lines)


def render_typed_clients(config: dict) -> str:
    service_items = sorted(config.get("services", {}).items())
    lines = [
        "--!strict",
        "-- Generated by scripts/generate.py. Do not edit directly.",
        "",
    ]
    if service_items:
        lines.extend(['local Channel = require(script.Parent.Parent.Channel)', ""])
    lines.extend([
        "export type Signal<T... = ...any> = {",
        "\tFire: (self: Signal<T...>, T...) -> (),",
        "\tConnect: (self: Signal<T...>, (T...) -> ()) -> RBXScriptConnection,",
        "}",
        "export type Property<T> = {",
        "\tGet: (self: Property<T>) -> T,",
        "\tObserve: (self: Property<T>, (T) -> ()) -> { Disconnect: (self: any) -> () },",
        "}",
        "",
    ])
    service_names = []
    for service_name, service in service_items:
        service_names.append(service_name)
        lines.append(f"export type {service_name} = {{")
        for method_name, method in sorted(service.get("methods", {}).items()):
            args = ", ".join(method.get("arguments", []))
            returns = ", ".join(method.get("returns", []))
            lines.append(
                f"\t{method_name}: (self: {service_name}, {args}) -> ({returns}),"
                if args
                else f"\t{method_name}: (self: {service_name}) -> ({returns}),"
            )
        for signal_name, details in sorted(service.get("signals", {}).items()):
            arguments = signal_arguments(details)
            argument_types = ", ".join(arg.split(":", 1)[-1].strip() for arg in arguments) or "...any"
            lines.append(f"\t{signal_name}: Signal<{argument_types}>,")
        for property_name, property_type in sorted(service.get("properties", {}).items()):
            lines.append(f"\t{property_name}: Property<{property_type}>,")
        lines.extend(["}", ""])

    if service_names:
        overloads = [
            f'((serviceName: {render_luau_string(service_name)}, timeout: number?) -> {service_name})'
            for service_name in service_names
        ]
        lines.append("export type BuildClient = " + " &\n\t".join(overloads))
        lines.append("export type Clients = {")
        lines.append("\tBuildClient: BuildClient,")
        for service_name in service_names:
            lines.append(f"\t{service_name}: (timeout: number?) -> {service_name},")
        lines.extend(["}", "", "local Clients: Clients = {"])
        lines.append("\tBuildClient = Channel.BuildClient :: any,")
        for service_name in service_names:
            lines.extend(
                [
                    f"\t{service_name} = function(timeout: number?): {service_name}",
                    f"\t\treturn Channel.BuildClient({render_luau_string(service_name)}, timeout) :: any",
                    "\tend,",
                ]
            )
        lines.extend(["}", "", "return table.freeze(Clients)", ""])
    else:
        lines.extend(
            [
                "export type Clients = {}",
                "",
                "local Clients: Clients = {}",
                "return table.freeze(Clients)",
                "",
            ]
        )
    return "\n".join(lines)


def render_manifest(config: dict) -> str:
    services = {}
    for service_name, service in sorted(config.get("services", {}).items()):
        remotes = []
        entries = []
        entries.extend((name, "Method", "RemoteFunction") for name in service.get("methods", {}))
        for name, details in service.get("signals", {}).items():
            remote_class = "UnreliableRemoteEvent" if isinstance(details, dict) and details.get("unreliable") else "RemoteEvent"
            entries.append((name, "Signal", remote_class))
        entries.extend((name, "Property", "Property") for name in service.get("properties", {}))
        for name, kind, remote_class in sorted(entries):
            remotes.append({"name": name, "kind": kind, "class": remote_class})
        services[service_name] = {"remotes": remotes}
    return json.dumps({"protocol": 1, "version": config["package"]["version"], "services": services}, indent=2) + "\n"


def render_runtime_manifest(config: dict) -> str:
    if not config.get("services"):
        return "--!strict\n-- Generated by scripts/generate.py. Do not edit directly.\n\nreturn table.freeze({})\n"
    lines = [
        "--!strict",
        "-- Generated by scripts/generate.py. Do not edit directly.",
        "",
        "return table.freeze({",
    ]
    for service_name, service in sorted(config.get("services", {}).items()):
        entries = []
        entries.extend((name, "Method", "RemoteFunction") for name in service.get("methods", {}))
        for name, details in service.get("signals", {}).items():
            remote_class = "UnreliableRemoteEvent" if isinstance(details, dict) and details.get("unreliable") else "RemoteEvent"
            entries.append((name, "Signal", remote_class))
        entries.extend((name, "Property", "Property") for name in service.get("properties", {}))
        entries.sort(key=lambda entry: entry[0])
        lines.append(f"\t[{render_luau_string(service_name)}] = table.freeze({{")
        for name, kind, remote_class in entries:
            lines.append(
                f"\t\ttable.freeze({{ Name = {render_luau_string(name)}, Kind = {render_luau_string(kind)}, Class = {render_luau_string(remote_class)} }}),"
            )
        lines.append("\t}),")
    lines.extend(["})", ""])
    return "\n".join(lines)


def render_wally(config: dict) -> str:
    package = config["package"]
    authors = ", ".join(render_luau_string(author) for author in package["authors"])
    repository = package.get("repository")
    include = package.get("include", [])
    repository_line = f"repository = {render_luau_string(repository)}\n" if repository else ""
    include_lines = ""
    if include:
        include_lines = "include = [\n" + "".join(f"    {render_luau_string(path)},\n" for path in include) + "]\n"
    return f'''# Generated by scripts/generate.py. Edit thread.config.json instead.
[package]
name = {render_luau_string(package["name"])}
version = {render_luau_string(package["version"])}
description = {render_luau_string(package["description"])}
license = {render_luau_string(package["license"])}
realm = {render_luau_string(package["realm"])}
authors = [{authors}]
registry = "https://github.com/UpliftGames/wally-index"
{repository_line}{include_lines}'''


def render_doc_version(content: str, version: str) -> str:
    if not DOC_VERSION_PATTERN.search(content):
        raise ValueError("documentation page is missing its version badge")
    return DOC_VERSION_PATTERN.sub(rf'\g<1>v{version}\g<2>', content)


def validate(config: dict) -> None:
    package = config.get("package", {})
    required = ("name", "version", "description", "license", "realm", "authors")
    missing = [key for key in required if key not in package]
    if missing:
        raise ValueError("missing package fields: " + ", ".join(missing))
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?", package["version"]):
        raise ValueError("package.version must be semantic version text")
    if not isinstance(package["authors"], list) or not package["authors"] or not all(isinstance(author, str) and author for author in package["authors"]):
        raise ValueError("package.authors must be a non-empty array of strings")
    if "repository" in package and (not isinstance(package["repository"], str) or not package["repository"]):
        raise ValueError("package.repository must be a non-empty string")
    if "include" in package and (
        not isinstance(package["include"], list)
        or not package["include"]
        or not all(isinstance(path, str) and path for path in package["include"])
    ):
        raise ValueError("package.include must be a non-empty array of strings")
    services = config.get("services", {})
    if not isinstance(services, dict):
        raise ValueError("services must be an object")
    for service_name, service in services.items():
        if not isinstance(service_name, str) or not LUAU_IDENTIFIER.fullmatch(service_name):
            raise ValueError(f"service name {service_name!r} is not a valid Luau identifier")
        if not isinstance(service, dict):
            raise ValueError(f"service {service_name!r} must be an object")
        groups = {}
        for group_name in ("methods", "signals", "properties"):
            group = service.get(group_name, {})
            if not isinstance(group, dict):
                raise ValueError(f"{service_name}.{group_name} must be an object")
            groups[group_name] = group
            for member_name in group:
                if not isinstance(member_name, str) or not LUAU_IDENTIFIER.fullmatch(member_name):
                    raise ValueError(f"{service_name}.{member_name!s} is not a valid Luau identifier")
        all_names = [name for group in groups.values() for name in group]
        if len(all_names) != len(set(all_names)):
            raise ValueError(f"service {service_name!r} uses the same member name in multiple groups")
        for method_name, method in groups["methods"].items():
            if not isinstance(method, dict):
                raise ValueError(f"{service_name}.{method_name} must be an object")
            for field in ("arguments", "returns"):
                values = method.get(field, [])
                if not isinstance(values, list) or not all(isinstance(value, str) and value.strip() for value in values):
                    raise ValueError(f"{service_name}.{method_name}.{field} must be an array of non-empty strings")
        for signal_name, details in groups["signals"].items():
            if not isinstance(details, (list, dict)):
                raise ValueError(f"{service_name}.{signal_name} must be an argument array or object")
            if isinstance(details, dict) and set(details) - {"arguments", "unreliable"}:
                raise ValueError(f"{service_name}.{signal_name} has unknown options")
            if isinstance(details, dict) and not isinstance(details.get("unreliable", False), bool):
                raise ValueError(f"{service_name}.{signal_name}.unreliable must be a boolean")
            arguments = signal_arguments(details)
            if not isinstance(arguments, list) or not all(isinstance(value, str) and value.strip() for value in arguments):
                raise ValueError(f"{service_name}.{signal_name}.arguments must be an array of non-empty strings")
        for property_name, property_type in groups["properties"].items():
            if not isinstance(property_type, str) or not property_type.strip():
                raise ValueError(f"{service_name}.{property_name} must contain a non-empty Luau type")


def generated_outputs(config: dict) -> dict[Path, str]:
    outputs = {
        ROOT / "src" / "Generated" / "Metadata.luau": render_metadata(config),
        ROOT / "src" / "Generated" / "ServiceManifest.luau": render_runtime_manifest(config),
        ROOT / "src" / "Generated" / "Clients.luau": render_typed_clients(config),
        ROOT / "generated" / "ClientTypes.luau": render_client_types(config),
        ROOT / "generated" / "ServiceManifest.json": render_manifest(config),
        ROOT / "wally.toml": render_wally(config),
    }
    version = config["package"]["version"]
    for path in (ROOT / "docs").glob("*.html"):
        current = path.read_text(encoding="utf-8")
        try:
            outputs[path] = render_doc_version(current, version)
        except ValueError as error:
            raise ValueError(f"{path.relative_to(ROOT)}: {error}") from error
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--tag", help="verify a release tag such as v1.2.3")
    args = parser.parse_args()

    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    validate(config)
    outputs = generated_outputs(config)
    stale = []
    for path, expected in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != expected:
            stale.append(path.relative_to(ROOT))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8", newline="\n")

    tag = args.tag or (os.environ.get("GITHUB_REF_NAME") if os.environ.get("GITHUB_REF_TYPE") == "tag" else None)
    if tag and tag != "v" + config["package"]["version"]:
        print(f"tag {tag!r} does not match package version v{config['package']['version']}", file=sys.stderr)
        return 1
    if args.check and stale:
        print("generated files are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    if not args.check:
        print(f"generated {len(outputs)} files for v{config['package']['version']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
